version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
        - '5000:5000'
    #If we self host the mysql database, we need to uncomment this
    #depends_on:
    #  - mysqlminitwit

  flagtool:
    image: ${DOCKER_USERNAME}/flag-tool
    container_name: flag-tool
    networks:
      - main
    command: tail -f /dev/null
    #If we self host the mysql database, we need to uncomment this
    #depends_on:
    #  - mysqlminitwit